dist: focal
sudo: required
language: node_js
node_js:
  # Highest Node version that sticks with npm 8.x; npm 9 doesn't play well on Travis. 
  - "18.13.0"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-8

env:
  - CXX=g++-8

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev
  - cd ${TRAVIS_BUILD_DIR}

script:
  - npx eslint .
