sudo: required
language: node_js
node_js:
  - "16.20.1"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9

env:
  - CXX=g++-4.9

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libgif-dev
  - cd ${TRAVIS_BUILD_DIR}

script:
  - npx eslint .
